### ISSUE TITLE
No Values in Output of proj_inv Function

### ISSUE THREAD

**Issue by mali-rcx** [nguyennico/planr#10]
Hi Nico - 

I am trying to use the proj_inv function of your package. In my output I am getting values, but in the later months of the data the output gives me no values. This happens in the Safety Stocks, Maximum Stocks, Ratio PI vs Min, and Ratio PI vs Max columns. I have attached a screenshot showing how there are no values in my output. 

![proj_invError](https://github.com/nguyennico/planr/assets/144825796/a1f379ee-b05c-4a4b-a7f0-0997e1fb0bf7)

The dataset I am using is attached below: 
[Forecast Practice.csv](https://github.com/nguyennico/planr/files/13297418/Forecast.Practice.csv)

And here is my code:
library(planr)
library(dplyr)

data1 <- read.csv("Forecast Practice.csv", header = TRUE)
head(data1)
names(data1)
data1$Date <- as.Date(data1$Date, format = "%Y-%m-%d")
colnames(data1) <- c("Period", "Demand", "Opening", "Supply", "Min.Cov", "Max.Cov", "DFU")

str(data1)

Calculated_Inv2 <- light_proj_inv(
  data = data1,
  DFU = DFU,
  Period = Period,
  Demand = Demand,
  Opening = Opening,
  Supply = Supply
)

View(Calculated_Inv2)

Calculated_Inv3 <- proj_inv(
  data = data1,
  DFU = DFU,
  Period = Period,
  Demand = Demand,
  Opening = Opening,
  Supply = Supply,
  Min.Cov = Min.Cov,
  Max.Cov = Max.Cov
)

View(Calculated_Inv3)

**Comment by nguyennico** [comment]
Hello Mali,
Yes indeed, it's because the files contains 12 periods of time.
 In order to calculate the parameters (min & max), we need some figures in the [sales] (forecasts) variables. 
The calculation will "stop" (displaying a NA) at the end of the horizon (before the 12th period) , because there are not enough values to perform those calculations.
Can you try with a longer horizon (providing [sales] figures over more periods of time), for example 24 periods ? 
It should be working fine normally.

Thank you,
Cheers,
Nico
